// Auto-generated by `supabase gen types typescript --local`.
// Regenerate after every migration via `pnpm --filter @ai-job-bot/db db:gen-types`.
// Phase 0: placeholder — no tables yet.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
